filename = 'build/UDPLogViewer.dmg'
volume_label = 'UDPLogViewer'
format = 'UDZO'
filesystem = 'HFS+'
size = None
files = ['build/UDPLogViewer.app']
symlinks = {'Applications': '/Applications'}
icon_locations = {'UDPLogViewer.app': (140, 170), 'Applications': (420, 170)}
icon = '/Users/bernhardklein/workspace/python/udp-viewer/packaging/macos/app.icns'
background = None
show_status_bar = False
show_tab_view = False
show_pathbar = False
show_sidebar = False
sidebar_width = None
default_view = 'icon-view'
show_icon_preview = False
include_icon_view_settings = 'auto'
include_list_view_settings = 'auto'
arrange_by = None
grid_offset = (0, 0)
grid_spacing = 100
scroll_position = (0, 0)
label_pos = 'bottom'
text_size = 16
icon_size = 128
icon_locations = {'UDPLogViewer.app': (140, 170), 'Applications': (420, 170)}
list_sort_by = None
list_use_relative_dates = None
list_calculate_all_sizes = None
license = None
