name: Bug report
description: Report a bug in the system
title: "[BUG] "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: "## Debug Information"
  - type: input
    id: version
    attributes:
      label: Firmware Version
      placeholder: 0.15.3 / 0.16.0 / ...
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug clearly
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      options:
        - Main log screen
        - PLOT visualization/config
        - LOGIC visualization/config
        - Preferences
