name: New feature
description: Describe this new feature
title: "[FEATURE] "
labels: ["feature"]

body:
  - type: markdown
    attributes:
      value: "## New Feature is needed...."
  - type: input
    id: version
    attributes:
      label: Current Firmware Version
      placeholder: 0.15.3 / 0.16.0 / ...
  - type: textarea
    id: description
    attributes:
      label: Describe this feature
      description: as clearly as possible
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      options:
        - Other (new)
        - Main log screen
        - PLOT visualization/config
        - LOGIC visualization/config
        - Preferences
        - Logging
